- name: create-vms
  block:
    -  ansible.builtin.shell: -|
        qm clone {{ origin-template-id }} {{ next_vm_id }} --name {{ item.name }} --full true --target {{ item.target_node }}
        qm set {{ next_vm_id }} --cores {{ item.cores }} --memory {{ item.memory }} --net0 {{ item.network }}

    - name: start vm
      ansible.builtin.shell: -|
        qm start {{ item.name }}
      when: item.start == true
  with_items: "{{ vms }}"